---
- name: Deploying RaspberryPi Custom API
  hosts: all
  connection: ssh

  vars:
    ansible_ssh_user: pi
    ansible_become: yes
    gopath: "/Users/rebelit/go"
    goroot: "/usr/local/opt/go/libexec"

  tasks:
  - name: Compile the application
    shell: "GOOS=linux GOARCH=arm go build -o main ."
    environment:
      GOPATH: "{{ gopath }}"
      GOROOT: "{{ goroot }}"
    delegate_to: 127.0.0.1

  - name: Create folder
    file:
      path: "/etc/api/"
      state: directory
      mode: 0644

  - name: Copy executable
    copy:
      src: "main"
      dest: "/etc/api/main"
      mode: a+x

  - name: Copy Configuration
    copy:
      src: "api_config.json"
      dest: "/etc/api/api_config.json"
      mode: 0644

  - name: Copy Service Files
    copy:
      src: "ansible_web-api.service"
      dest: "/usr/lib/systemd/system/web-api.service"

  - name: Unleash the daemon (make new service known)
    command: systemctl daemon-reload

  - name: restart service
    service:
      name: web-api
      state: restarted
      enabled: true